// colors_batch2.js — mau variant dot 2, append dan theo batch
const COLORS = {
'Angular Geometric Eyeglasses': [['#E8C4CC','Hồng trong'],['#8A8A8A','Xám lấp lánh']],
'Chic Oversized Square Sunglasses': [['#1A1A1A','Đen'],['#8B4513','Đồi mồi'],['#4A2418','Nâu ombre']],'Classic Round Metal Eyeglasses': [['#C0C0C0','Bạc hồng nhạt'],['#C0C0C0','Bạc'],['#D4C08A','Vàng gold']],
'Classic Square Plastic Eyeglasses': [['#6E6E66','Xám khói trong'],['#1A1A1A','Đen']],
'Color Block Shape Sunglasses': [['#9DA8E8','Tím lavender'],['#1A1A1A','Đen'],['#8B5A2B','Đồi mồi'],['#7FD4B0','Xanh bạc hà'],['#F0DCC0','Be champagne']],
'Cut-Out Rectangular Metal Eyeglasses': [['#7B4E9E','Tím violet'],['#C0392B','Đỏ ruby'],['#3ABBA8','Xanh ngọc'],['#B85C9E','Hồng tím']],
'Feminine Square Metal Eyeglasses': [['#C9A0B8','Hồng pastel'],['#1A1A1A','Đen nhám'],['#A8263E','Đỏ đô']],
'Geometric Hybrid Metal Eyeglasses': [['#8B7340','Đồi mồi vàng'],['#5A5A5A','Xám gunmetal'],['#C9A227','Gold đen']],
'Geometric Wire-Frame Metal Glasses': [['#C0C0C0','Bạc'],['#B8B8C4','Bạc khói']],
'Glassity Classic': [['#1A1A1A','Đen tím'],['#6B3A1F','Đồi mồi'],['#8A5A48','Nâu ombre']],
'Glassity Oval Frame': [['#1A1A1A','Đen'],['#4A2645','Tím vân'],['#5A3E2E','Nâu']],
'Glassity Soft Mini': [['#1A1A1A','Đen'],['#2E4372','Xanh navy'],['#4A3228','Nâu đậm']],
'Glassity Vision Air': [['#D4B978','Vàng gold'],['#C48FA8','Hồng rose'],['#C0C0C0','Bạc'],['#8A5C42','Đồng cổ']],
'Glassity Vision Round': [['#E8E4DC','Trong suốt đồi mồi'],['#D4BBA8','Be hồng']],
'Glassity Vision Square': [['#5C3A21','Đồi mồi'],['#9A9DA3','Xám trong'],['#1A1A1A','Đen']],
'Hexagonal Windsor Rim Eyeglasses': [['#E8B4A0','Vàng hồng ngọc trai'],['#D4AF37','Vàng gold đồi mồi']],
'Minimalist Wire-Frame Sunglasses': [['#1A1A1A','Đen'],['#4A3428','Nâu socola'],['#E3B8C0','Hồng pastel']],
'Modern Butterfly Eyeglasses': [['#B0906E','Nâu be trong'],['#B48EB4','Tím khói']],
'Modern Oval Cat-Eye Metal Eyeglasses': [['#C0C0C0','Bạc'],['#D4AF37','Vàng gold'],['#C9CBCF','Bạc hồng']],
'Old Cat-Eye Acetate Sunglasses': [['#1A1A1A','Đen'],['#5C3A21','Đồi mồi']],
'Oversized Rounded Cat-Eye Sunglasses': [['#8A7A62','Nâu khaki'],['#1A1A1A','Đen'],['#6B8F5A','Xanh lá'],['#FFFFFF','Trắng'],['#EDE6C4','Vàng kem']],
'Polycarbonate Cat-Eye Eyeglasses': [['#1A1A1A','Đen'],['#B14FC5','Tím trong'],['#E8D5A3','Da báo kem'],['#D32F2F','Đỏ phối đen']],
'Rectangle Tech-Poly Sunglasses': [['#5C3A21','Đồi mồi nâu'],['#1A1A1A','Đen tráng gương đỏ'],['#1F3A93','Xanh navy tráng gương']],
'Rivet Square Eyeglasses': [['#EDEDED','Trong suốt'],['#8E2430','Đỏ đô'],['#2C3460','Xanh navy đồi mồi']],
'Round Tortoise Metal Sunglasses': [['#4A5A3A','Đồi mồi xanh rêu'],['#8B6914','Đồi mồi vàng']],
'Rounded-Square Tr90 Eyeglasses': [['#F4C2D0','Hồng trong'],['#1A1A1A','Đen phối đỏ'],['#EFEFEF','Trong suốt'],['#7A6248','Nâu trong']],
'Sleek Cat-Eye Tinted Sunglasses': [['#1A1A1A','Đen'],['#C6CC93','Xanh pistachio'],['#FFFFFF','Trắng']],
'Slim Metal Cat-Eye Eyeglasses': [['#E8B4A0','Vàng hồng'],['#6A5ACD','Tím'],['#E6D9A8','Vàng kem']],
'Slim Oval Metal Cat-Eye Eyeglasses': [['#C0C0C0','Bạc'],['#D4C08A','Vàng gold']],
'Slim Square Dual-Tone Eyeglasses': [['#A0E8DC','Nâu phối xanh mint'],['#D8A0B8','Đồi mồi hồng'],['#B8A88E','Đồi mồi be']],
'Slim Square Metal Eyeglasses': [['#2C4A6E','Xanh navy'],['#C0C0C0','Bạc'],['#8B6242','Nâu đồng']],
'Soft Square Eyeglasses': [['#5E7A6E','Xanh rêu ombre'],['#B85C38','Cam gạch phối xám'],['#1A1A1A','Đen'],['#EFEFEF','Trong suốt']],
'Soft-Curved Oval Cat-Eye Glasses': [['#C9A0A8','Bạc tròng hồng'],['#C0C0C0','Bạc'],['#AEB2B8','Bạc tròng xám']],
'Sparkle Browline Eyeglasses': [['#C0C0C0','Bạc lấp lánh'],['#3A3A3A','Đen lấp lánh'],['#8B6D5C','Nâu lấp lánh']],
'Thick Square Star Eyeglasses': [['#1A1A1A','Đen'],['#9BA0A8','Da báo xám trong']],
'Translucent Cat-Eye Eyeglasses': [['#EFEFEF','Trong suốt'],['#F4C2D0','Hồng trong']],
'Urban Panto Eyeglasses': [['#1A1A1A','Đen'],['#5C3A45','Nâu vân gỗ'],['#2C4A7E','Xanh navy vân gỗ']],
'Urban Square Eyeglasses': [['#1A1A1A','Đen phối vàng gold'],['#F4C2D0','Hồng trong'],['#8B6242','Đồi mồi phối vàng gold']],
};
module.exports = COLORS;
